// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResumeBuilder.Data;

#nullable disable

namespace ResumeBuilder.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241128165324_addVisibility")]
    partial class addVisibility
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // modelBuilder.Entity("ResumeBuilder.Models.Certifications", b =>
            //     {
            //         b.Property<int>("CertificationID")
            //             .ValueGeneratedOnAdd()
            //             .HasColumnType("int");

            //         SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CertificationID"));

            //         b.Property<string>("Issuer")
            //             .IsRequired()
            //             .HasColumnType("nvarchar(max)");

            //         b.Property<string>("Name")
            //             .IsRequired()
            //             .HasColumnType("nvarchar(max)");

            //         b.Property<int>("UserID")
            //             .HasColumnType("int");

            //         b.HasKey("CertificationID");

            //         b.ToTable("Certifications");
            //     });

            // modelBuilder.Entity("ResumeBuilder.Models.Education", b =>
            //     {
            //         b.Property<int>("EducationID")
            //             .ValueGeneratedOnAdd()
            //             .HasColumnType("int");

            //         SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EducationID"));

            //         b.Property<string>("Degree")
            //             .IsRequired()
            //             .HasColumnType("nvarchar(max)");

            //         b.Property<int>("EndingYear")
            //             .HasColumnType("int");

            //         b.Property<decimal>("GPA")
            //             .HasColumnType("decimal(18,2)");

            //         b.Property<string>("InstituteName")
            //             .IsRequired()
            //             .HasColumnType("nvarchar(max)");

            //         b.Property<int>("StartingYear")
            //             .HasColumnType("int");

            //         b.Property<int>("UserID")
            //             .HasColumnType("int");

            //         b.HasKey("EducationID");

            //         b.ToTable("Education");
            //     });

            // modelBuilder.Entity("ResumeBuilder.Models.Projects", b =>
            //     {
            //         b.Property<int>("ProjectID")
            //             .ValueGeneratedOnAdd()
            //             .HasColumnType("int");

            //         SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectID"));

            //         b.Property<string>("Description")
            //             .IsRequired()
            //             .HasColumnType("nvarchar(max)");

            //         b.Property<DateTime>("EndDate")
            //             .HasColumnType("datetime2");

            //         b.Property<string>("Name")
            //             .IsRequired()
            //             .HasColumnType("nvarchar(max)");

            //         b.Property<string>("Role")
            //             .IsRequired()
            //             .HasColumnType("nvarchar(max)");

            //         b.Property<DateTime>("StartDate")
            //             .HasColumnType("datetime2");

            //         b.Property<int>("UserID")
            //             .HasColumnType("int");

            //         b.HasKey("ProjectID");

            //         b.ToTable("Projects");
            //     });

            // modelBuilder.Entity("ResumeBuilder.Models.Skills", b =>
            //     {
            //         b.Property<int>("SkillID")
            //             .ValueGeneratedOnAdd()
            //             .HasColumnType("int");

            //         SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillID"));

            //         b.Property<string>("Name")
            //             .IsRequired()
            //             .HasColumnType("nvarchar(max)");

            //         b.Property<int>("UserID")
            //             .HasColumnType("int");

            //         b.HasKey("SkillID");

            //         b.ToTable("Skills");
            //     });

            // modelBuilder.Entity("ResumeBuilder.Models.User", b =>
            //     {
            //         b.Property<int>("UserID")
            //             .ValueGeneratedOnAdd()
            //             .HasColumnType("int");

            //         SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

            //         b.Property<string>("Email")
            //             .IsRequired()
            //             .HasColumnType("nvarchar(max)");

            //         b.Property<string>("PasswordHash")
            //             .IsRequired()
            //             .HasColumnType("nvarchar(max)");

            //         b.HasKey("UserID");

            //         b.ToTable("Users");
            //     });

            modelBuilder.Entity("ResumeBuilder.Models.UserDetails", b =>
                {
                    b.Property<int>("DetailsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailsID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<bool>("Visibility")
                        .HasColumnType("bit");

                    b.HasKey("DetailsID");

                    b.ToTable("UserDetails");
                });

            // modelBuilder.Entity("ResumeBuilder.Models.WorkExperience", b =>
            //     {
            //         b.Property<int>("WorkExperienceID")
            //             .ValueGeneratedOnAdd()
            //             .HasColumnType("int");

            //         SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkExperienceID"));

            //         b.Property<string>("CompanyName")
            //             .IsRequired()
            //             .HasColumnType("nvarchar(max)");

            //         b.Property<string>("Description")
            //             .IsRequired()
            //             .HasColumnType("nvarchar(max)");

            //         b.Property<DateTime>("EndDate")
            //             .HasColumnType("datetime2");

            //         b.Property<DateTime>("StartDate")
            //             .HasColumnType("datetime2");

            //         b.Property<string>("Title")
            //             .IsRequired()
            //             .HasColumnType("nvarchar(max)");

            //         b.Property<int>("UserID")
            //             .HasColumnType("int");

            //         b.HasKey("WorkExperienceID");

            //         b.ToTable("WorkExperience");
            //     });
#pragma warning restore 612, 618
        }
    }
}
